[loadbalancer]
database-server ansible_host=127.0.0.1 ansible_port=40115 internal_ip=192.168.1.115 ansible_user=root ansible_ssh_pass=root ansible_python_interpreter=/usr/bin/python3
k8s-master-1 ansible_host=127.0.0.1 ansible_port=40111 internal_ip=192.168.1.111 ansible_user=root ansible_ssh_pass=root ansible_python_interpreter=/usr/bin/python3
k8s-master-2 ansible_host=127.0.0.1 ansible_port=40112 internal_ip=192.168.1.112 ansible_user=root ansible_ssh_pass=root ansible_python_interpreter=/usr/bin/python3
k8s-master-3 ansible_host=127.0.0.1 ansible_port=40113 internal_ip=192.168.1.113 ansible_user=root ansible_ssh_pass=root ansible_python_interpreter=/usr/bin/python3
loadbalancer-k8s ansible_host=127.0.0.1 ansible_port=40110 internal_ip=192.168.1.110 ansible_user=root ansible_ssh_pass=root ansible_python_interpreter=/usr/bin/python3
rancher-server ansible_host=127.0.0.1 ansible_port=40114 internal_ip=192.168.1.114 ansible_user=root ansible_ssh_pass=root ansible_python_interpreter=/usr/bin/python3

[k8s_master_1]
k8s-master-1

[k8s_masters]
# list of k8s masters
k8s-master-1
k8s-master-2
k8s-master-3

[k8s_masters_except_first]
k8s-master-2
k8s-master-3

[loadbalancer]
loadbalancer-k8s

[rancher]
rancher-server

[database]
database-server
